//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelServices.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class voteLyEntities : DbContext
    {
        public voteLyEntities()
            : base("name=voteLyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answear> Answears { get; set; }
        public DbSet<AnswearScore> AnswearScores { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Voting> Votings { get; set; }
        public DbSet<VUser> VUsers { get; set; }
    }
}
