//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUser
    {
        public VUser()
        {
            this.Votings = new HashSet<Voting>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<Voting> Votings { get; set; }
    }
}
